name: flappy_translator
description: A tool which automatically generates Flutter localization resources from CSV and Excel files.
version: 2.0.0
homepage: https://github.com/smartnsoft/FlappyTranslator
repository: https://github.com/smartnsoft/FlappyTranslator
issue_tracker: https://github.com/smartnsoft/FlappyTranslator/issues

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  meta: ^1.8.0
  csv: ^6.0.0
  yaml: ^3.1.2
  dart_style: ^2.3.3
  excel: ^4.0.0

dev_dependencies:
  test: ^1.20.0
  lints: ^4.0.0
