name: flappy_translator
description: A tool which automatically generates Flutter localization resources from CSV and Excel files.
version: 2.0.0-nullsafety.2
homepage: https://github.com/smartnsoft/FlappyTranslator
repository: https://github.com/smartnsoft/FlappyTranslator
issue_tracker: https://github.com/smartnsoft/FlappyTranslator/issues

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  meta: ^1.3.0
  csv: ^5.0.0
  yaml: ^3.1.0
  dart_style: ^2.0.1
  excel: 2.0.0-null-safety-3

dev_dependencies:
  test: ^1.16.8
  pedantic: ^1.11.0
